# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FriendsList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FriendsList
  pod 'RealmSwift', '~>10.53.0'


  target 'FriendsListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FriendsListUITests' do
    # Pods for testing
  end

end
